### PR TITLE
Ready for review

### PR DESCRIPTION
**Pull request by maelfosso**
Hello reviewers,

I think it's ready for review.
Please, give me your point of view.

Thank you.

### CODE REVIEW

**Review by AdnanAfsari — CHANGES_REQUESTED** [review]
**Status: Changes Required**

Hello @maelfosso ✋ 

Nice work but you have to do few more things to get approval.

- [ ] User should be able  edit the details of a to-do item.

- [ ] App should use  localStorage to save todos between sessions.

- [ ] Priority does not get updated. it keeps high as default. Note: there is a type, it should be high not height.

- [ ] There should be a descriptive Readme.

Please make those changes and submit for another review.

Happy Coding
Adnan Afsari

**Comment by maelfosso** [comment]
Hello @AdnanAfsari 

Thank you for that awesome review.
Please, I have one question: You said **Priority does not get updated. it keeps high as default. Note: there is a type, it should be high not height.**: What do you mean please ?

Thanks.

**Review by AdnanAfsari — APPROVED** [review]
**Status: Approved**

Hello @maelfosso ✋ 

Nice work, Its a 👍 from me.

Happy Coding
Adnan Afsari

**Comment by maelfosso** [comment]
Thank you @AdnanAfsari  :smile:

**Pull request merged**
